### ISSUE TITLE
top, left, bottom shadow works great but right shadow are not working ?

### ISSUE THREAD

**Issue by yussefbens** [h6ah4i/android-materialshadowninepatch#13]
I thank you for the awesome library that save me a lot of time, I used the lib in a recyclerview but the right shadow aren't working while the top, left, bottom working great. I hope you give me a tip to fix this problem as you see this comment. 
![screenshot](https://cloud.githubusercontent.com/assets/11192475/13324334/1d46cb56-dbd5-11e5-8cd5-320eb6dbadcd.jpg)

**Comment by h6ah4i** [comment]
@yussef123  Hi. That seems weird to me. I have added an example which uses RecyclerView and confirmed this library can be used inside of RecyclerView.
- https://github.com/h6ah4i/android-materialshadowninepatch/tree/issue_13_recyclerview

<img src="https://cloud.githubusercontent.com/assets/2552365/13356040/b7e73346-dce6-11e5-9c30-1b5ab5216d16.png" width="150" />

If you still cannot find the solution yourself, could you upload a sample code which can reproduce the same issue?

Thanks.

**Comment by yussefbens** [comment]
I figure out that I have a problem in size of the grid list and the space aren't enough to draw the shadow.
Thank you for your help and sorry for disturbing you.

**Comment by h6ah4i** [comment]
No problem, I am glad to help :smile:
