### ISSUE TITLE
please add  View.isInEditMode()

### ISSUE THREAD

**Issue by pishguy** [h6ah4i/android-materialshadowninepatch#16]
when i try to desing UI i get error for rendering page, please add some `View.isInEditMode()` on yout class

**Comment by h6ah4i** [comment]
Hi. I believe I have already using `View.isInEditMode()` method. I do not see any rendering errors on Android Studio 2.2 RC. Which version of AS do you use? Also could you upload a sample code/project which can reproduce the issue? Thanks.

**Comment by pishguy** [comment]
Hi. i'm so sorry, problem resolved after invalidate caches and restart
android studio
